// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infrastructure
{
    public partial class FakeDataMaster
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public bool OnDelete { get; set; }
    }
}