version: '3.4'

services:
  warehouse:
    image: warehouse
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:80
      - 9229:80
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
