apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe -v convert -f docker-compose.yml -o exportk8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
   #  io.kompose.service: angular
    app: angular
  name: angular
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 80
  selector:
   #  io.kompose.service: angular
    app: angular
status:
  loadBalancer: {}
