version: '3.4'

services:

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
        - "5341:80"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
            SA_PASSWORD: "Aa!0977751021"
            ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    volumes:
      - doan-sqlserver:/data/db

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    volumes:
    - doan-redis:/data/db

  warehouse-api:
    image: ${REGISTRY:-doantotnghiep}/warehouse.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/WareHouse/WareHouse.API/Dockerfile
    depends_on:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${DOAN_WAREHOUSE_DB:-Server=sqldata;Database=WarehouseManagement;User Id=sa;Password=Aa!0977751021}
      - PATH_BASE=/warehouse-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5005:80"
      - "5006:81"
  master-api:
    image: ${REGISTRY:-doantotnghiep}/master:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Master/Master/Dockerfile
    depends_on:
      # - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${DOAN_WAREHOUSE_DB:-Server=sqldata;Database=MasterData;User Id=sa;Password=Aa!0977751021}
      - PATH_BASE=/warehouse-api
      - GRPC_PORT=81
      - PORT=80
    ports:
      - "5001:80"
      - "5000:81"
   
volumes:
  doan-sqlserver:
    external: false
  doan-redis:
    external: false

 