// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Infrastructure.Configurations
{
    public partial class ListAuthozireRoleByUserConfiguration : IEntityTypeConfiguration<ListAuthozireRoleByUser>
    {
        public void Configure(EntityTypeBuilder<ListAuthozireRoleByUser> entity)
        {
            entity.ToTable("ListAuthozireRoleByUser");

            entity.Property(e => e.Id).HasMaxLength(50);

            entity.Property(e => e.ListAuthozireId).HasMaxLength(250);

            entity.Property(e => e.UserId).HasMaxLength(250);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ListAuthozireRoleByUser> entity);
    }
}
