// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Infrastructure.Configurations
{
    public partial class ListAppConfiguration : IEntityTypeConfiguration<ListApp>
    {
        public void Configure(EntityTypeBuilder<ListApp> entity)
        {
            entity.ToTable("ListApp");

            entity.Property(e => e.Id).HasMaxLength(50);

            entity.Property(e => e.Description).HasMaxLength(250);

            entity.Property(e => e.IsAPI).HasDefaultValueSql("((1))");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.SoftShow).HasDefaultValueSql("((1))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ListApp> entity);
    }
}
