// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Infrastructure.Configurations
{
    public partial class UserMasterConfiguration : IEntityTypeConfiguration<UserMaster>
    {
        public void Configure(EntityTypeBuilder<UserMaster> entity)
        {
            entity.ToTable("UserMaster");

            entity.Property(e => e.Id).HasMaxLength(50);

            entity.Property(e => e.InActive)
                .IsRequired()
                .HasDefaultValueSql("((1))");

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);

            //entity.Property(e => e.WarehouseId).HasMaxLength(int.MaxValue);
            //entity.Property(e => e.ListWarehouseId).HasMaxLength(250);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserMaster> entity);
    }
}
