// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Share.BaseCore.BaseNop;

namespace Infrastructure
{
    public partial class ListAuthozireRoleByUser : BaseEntity
    {
        public string ListAuthozireId { get; set; }
        public string UserId { get; set; }
       // public string AppId { get; set; }
    }
}