// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace Infrastructure
{
    public partial class ListRoleByUser: BaseEntity
    {
        public string ListRoleId { get; set; }
        public string UserId { get; set; }
        public string AppId { get; set; }

    }
}