// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Share.BaseCore;
using Share.BaseCore.BaseNop;
using System;
using System.Collections.Generic;

namespace Infrastructure
{
    public partial class ListRole : BaseEntity
    {
        public string AppId { get; set; }
        public string Name { get; set; }
        public bool InActive { get; set; }
        public string Description { get; set; }
        public string Key { get; set; }
        public string ParentId { get; set; }
        public int? SoftShow { get; set; }
        public bool? IsAPI { get; set; }
    }
}