// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Share.BaseCore.BaseNop;

namespace Infrastructure
{
    public partial class ListAuthozire : BaseEntity
    {
        public string Name { get; set; }
        public bool InActive { get; set; }
        public string Description { get; set; }
        public string? ParentId { get; set; }
        public int? SoftShow { get; set; }
    }
}