apiVersion: v1
kind: Service
metadata:
  name: {{ include "master-api.fullname" . }}
  labels:
    {{- include "master-api.labels" . | nindent 4 }}
  # app: {{ template  "master-api.name" . }}
  # chart: {{ template  "master-api.chart" . }}
  # release: {{ .Release.Name }}
  # heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "master-api.selectorLabels" . | nindent 4 }}
