_format_version: "1.1"
#https://github.com/tuannguyenssu/kong-examples
# Ví dụ cấu hình một APIs đơn giản với Kong


# Cấu hình các Services và Routes

services:
- name: api-mt
  url: http://api-mt:80/
  routes:
  - name: api-mt
    methods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - HEAD
    - DELETE
    paths:
    - /api-mt
    tags:
    - api-mt
    protocols:
    - http
    - https
    https_redirect_status_code: 301
    regex_priority: 0
    strip_path: true
    preserve_host: false
    path_handling: v1

- name: api-wh
  url: http://apimt-4681-service.k8sqrt.svc:80/
  tags:
  - api-wh
  retries: 5
  write_timeout: 60000
  routes:
  - name: api-wh
    methods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - HEAD
    - DELETE
    paths:
    - /api-wh
    protocols:
    - http
    - https
    https_redirect_status_code: 301
    regex_priority: 0
    strip_path: true
    preserve_host: false

- name: api-mt1
  url: http://api-mt/
  routes:
  - name: api-mt1
    methods:
    - OPTIONS
    - GET
    - POST
    - PUT
    - HEAD
    - DELETE
    paths:
    - /api-mt1
    tags:
    - api-mt1
    protocols:
    - http
    - https
    https_redirect_status_code: 301
    regex_priority: 0
    strip_path: true
    preserve_host: false
    path_handling: v1
