# https://github.com/elastic/logstash-docker
#FROM docker.elastic.co/logstash/logstash:7.13.2
FROM docker.elastic.co/logstash/logstash-oss:6.0.0
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
# RUN logstash-plugin install logstash-input-http
# RUN logstash-plugin install logstash-input-jdbc
# RUN rm -f /usr/share/logstash/pipeline/logstash.conf
# USER root 

# COPY mssql-jdbc-10.2.1.jre8.jar /usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-10.2.1.jre8.jar
