name: Build and Publish NuGet 

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
          cache: true

      - name: Build
        run: dotnet build -c Release

      - name: Package
        run: dotnet pack -c Release

      - name: Publish NuGet Package
        run: dotnet nuget push **/*.nupkg --source Dev-97-Loop
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
