name: Build and Publish NuGet 

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x


      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ./Share.Base.Service/Share.Base.Service.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Build and Push Share.Base.Service
        run: |
            cd ./Share.Base.Service
            dotnet restore --locked-mode
            dotnet build -c Release
            dotnet pack -c Release
            dotnet nuget push  **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
    
      - name: Build and Push Share.Base.Core
        run: |
            cd ./Share.Base.Core
            dotnet restore --locked-mode
            dotnet build -c Release
            dotnet pack -c Release
            dotnet nuget push  **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
      
