name: Build and Publish NuGet 


on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Set working directory
        run: cd ./Share.Base.Service

      - name: Restore NuGet packages
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release

      - name: Pack NuGet package
        run: dotnet pack -c Release

      - name: Publish NuGet Package
        run: |
         nuget setApiKey ${{ secrets.NUGET_API_KEY }}
         dotnet nuget push  **/*.97.nupkg --api-key oy2k4cvkvy5xj5woh4bajz3id4eonk4ujomg6z4fhpjitq --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
